name: Update Website

on:
  workflow_run:
    workflows: ["Update WFEs"]
    types:
      - completed
  workflow_dispatch:

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: website
      - name: Fetch main branch
        run: |
          git fetch --depth=2
          git switch main
          git checkout website
      - name: Update indexes
        run: |
          ./update-website.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update website
          commit_user_name: Automated Commit
          commit_user_email: ""
          commit_author: Automated Commit <>
